export const LOAD_DATA = 'LOAD_DATA'
export const REQUESTING_DATA = 'REQUESTING_DATA'
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS'
export const REQUEST_FAILED = 'REQUEST_FAILED'

export const UPDATE_SEARCH = 'UPDATE_SEARCH'
export const UPDATE_FILTERED_TOPICS = 'UPDATE_FILTERED_TOPICS'
